version: "3.7"

services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - .nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: .
        container_name: php
        volumes:
            - ./code:/code
    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"
    test_db:
        build: _mysql
        container_name: test_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"

